CREATE DATABASE PROJETO_DEV

USE PROJETO_DEV

CREATE TABLE FOODS (
  ID int NOT NULL AUTO_INCREMENT,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(255),
  PRICE DECIMAL(7,2),
  PRIMARY KEY (ID)
)

INSERT INTO FOODS (NAME, DESCRIPTION, PRICE)
VALUES ('Macarrao', 'Macarrao top das galaxias', 29.99)

SELECT * FROM foods